// <auto-generated />
using FinalDigicoApi.DBAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalDigicoApi.Migrations
{
    [DbContext(typeof(DBAccessor))]
    [Migration("20230602133743_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalDigicoApi.Objects.BasicOccupation", b =>
                {
                    b.Property<string>("selfRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("selfRef");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("FinalDigicoApi.Objects.BasicSkill", b =>
                {
                    b.Property<string>("selfRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("selfRef");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("FinalDigicoApi.Objects.OccationBasicSkill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasicOccupationselfRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsEssential")
                        .HasColumnType("bit");

                    b.Property<string>("skillselfRef")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BasicOccupationselfRef");

                    b.HasIndex("skillselfRef");

                    b.ToTable("occationBasicSkills");
                });

            modelBuilder.Entity("FinalDigicoApi.Objects.OccationBasicSkill", b =>
                {
                    b.HasOne("FinalDigicoApi.Objects.BasicOccupation", null)
                        .WithMany("Skills")
                        .HasForeignKey("BasicOccupationselfRef");

                    b.HasOne("FinalDigicoApi.Objects.BasicSkill", "skill")
                        .WithMany()
                        .HasForeignKey("skillselfRef");

                    b.Navigation("skill");
                });

            modelBuilder.Entity("FinalDigicoApi.Objects.BasicOccupation", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
